---
- name: Create agent conf
  template:
    src: "{{ role_path }}/templates/agent.yml"
    dest: "{{ tmp }}/sk-{{ skydive_role }}{{ play_hosts.index(inventory_hostname) * vhosts + item }}/conf"
  with_items: "{{ range(0, vhosts) | list }}"
  tags: configuration

- name: Create screen session
  include_role:
    name: common
    tasks_from: screen

- name: Start agent
  shell: |
    {% set ns_host = "sk-" + skydive_role + (play_hosts.index(inventory_hostname) * vhosts + item)|string %}
    {% set host_folder = tmp + "/sk-" + skydive_role + (play_hosts.index(inventory_hostname) * vhosts + item)|string %}

    screen -S skydive -X screen -t skydive-agent {{ item }} ip netns exec {{ ns_host }} sh -c "/tmp/skydive-bin agent -c "{{ host_folder }}/conf/agent.yml" 2>&1 | tee {{ host_folder }}/log/skydive.log"
  with_items: "{{ range(0, vhosts) | list }}"
