---
- name: Gather facts
  hosts: all
  remote_user: root
  become: true
  tasks:
    - include: "tasks/facts.yml"

- name: Deploy host
  hosts: analyzers
  remote_user: root
  become: true
  roles:
  - role: all
    tags: infrastructure

- name: Add gw
  hosts: gw
  remote_user: root
  become: true
  roles:
  - role: gw
    tags: infrastructure

- name: Deploy agents
  hosts: agents
  remote_user: root
  become: true
  roles:
  - role: all
    tags: infrastructure

- name: Start analyzers
  hosts: analyzers
  remote_user: root
  become: true
  roles:
  - analyzer

- name: Start agents
  hosts: agents
  remote_user: root
  become: true
  roles:
  - agent
