---
- name: Install common packages
  include_role:
    name: common
    tasks_from: package

- name: Cleanup
  include_role:
    name: common
    tasks_from: cleanup

- name: Create netns folder
  file:
    path: /var/run/netns
    state: directory
    mode: 0755

- name: Create mesh network
  include_role:
    name: common
    tasks_from: mesh

- name: Create fake host
  include_role:
    name: common
    tasks_from: fake-host
