---
- package:
    name: "{{ item }}"
    state: present
  with_items:
    - centos-release-openstack-pike
    - libselinux-python
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- package:
    name: "{{ item }}"
    state: present
  with_items:
    - openvswitch
    - bridge-utils
    - screen

- service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - openvswitch
